<?php

namespace Container32wZr7w;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_B7fVg6SService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.b7fVg6S' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.b7fVg6S'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'offre' => ['privates', '.errored..service_locator.b7fVg6S.App\\Entity\\Offre', NULL, 'Cannot autowire service ".service_locator.b7fVg6S": it references class "App\\Entity\\Offre" but no such service exists.'],
        ], [
            'offre' => 'App\\Entity\\Offre',
        ]);
    }
}
