<?php

namespace Container32wZr7w;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRating2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.fvmPtFf.App\Entity\Rating' shared service.
     *
     * @return \App\Entity\Rating
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.fvmPtFf": it references class "App\\Entity\\Rating" but no such service exists.');
    }
}
