<?php

namespace ContainerHFuxsma;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_BPGibOOService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.BPGibOO' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.BPGibOO'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'offre' => ['privates', '.errored..service_locator.BPGibOO.App\\Entity\\Offre', NULL, 'Cannot autowire service ".service_locator.BPGibOO": it references class "App\\Entity\\Offre" but no such service exists.'],
            'offreRepository' => ['privates', 'App\\Repository\\OffreRepository', 'getOffreRepositoryService', true],
        ], [
            'offre' => 'App\\Entity\\Offre',
            'offreRepository' => 'App\\Repository\\OffreRepository',
        ]);
    }
}
