<?php

namespace ContainerHFuxsma;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_PbvythWService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.PbvythW' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.PbvythW'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'rating' => ['privates', '.errored..service_locator.PbvythW.App\\Entity\\Rating', NULL, 'Cannot autowire service ".service_locator.PbvythW": it references class "App\\Entity\\Rating" but no such service exists.'],
            'ratingRepository' => ['privates', 'App\\Repository\\RatingRepository', 'getRatingRepositoryService', true],
        ], [
            'rating' => 'App\\Entity\\Rating',
            'ratingRepository' => 'App\\Repository\\RatingRepository',
        ]);
    }
}
