<?php

namespace ContainerXrI0aMK;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_FvmPtFfService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.fvmPtFf' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.fvmPtFf'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'rating' => ['privates', '.errored..service_locator.fvmPtFf.App\\Entity\\Rating', NULL, 'Cannot autowire service ".service_locator.fvmPtFf": it references class "App\\Entity\\Rating" but no such service exists.'],
        ], [
            'rating' => 'App\\Entity\\Rating',
        ]);
    }
}
