<?php

namespace ContainerLoBRsC4;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_JlB0BJgService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.jlB0BJg' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.jlB0BJg'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\ItineraireController::delete' => ['privates', '.service_locator.i7iqqrB', 'get_ServiceLocator_I7iqqrBService', true],
            'App\\Controller\\ItineraireController::edit' => ['privates', '.service_locator.i7iqqrB', 'get_ServiceLocator_I7iqqrBService', true],
            'App\\Controller\\ItineraireController::index' => ['privates', '.service_locator.K9TRytY', 'get_ServiceLocator_K9TRytYService', true],
            'App\\Controller\\ItineraireController::new' => ['privates', '.service_locator.K9TRytY', 'get_ServiceLocator_K9TRytYService', true],
            'App\\Controller\\ItineraireController::show' => ['privates', '.service_locator.FdDxxpr', 'get_ServiceLocator_FdDxxprService', true],
            'App\\Controller\\UtilisateurController::delete' => ['privates', '.service_locator.KzL3gdR', 'get_ServiceLocator_KzL3gdRService', true],
            'App\\Controller\\UtilisateurController::edit' => ['privates', '.service_locator.KzL3gdR', 'get_ServiceLocator_KzL3gdRService', true],
            'App\\Controller\\UtilisateurController::index' => ['privates', '.service_locator.JMejbpE', 'get_ServiceLocator_JMejbpEService', true],
            'App\\Controller\\UtilisateurController::new' => ['privates', '.service_locator.JMejbpE', 'get_ServiceLocator_JMejbpEService', true],
            'App\\Controller\\UtilisateurController::show' => ['privates', '.service_locator.r5W7ygF', 'get_ServiceLocator_R5W7ygFService', true],
            'App\\Controller\\VehiculeController::delete' => ['privates', '.service_locator.YdyC4xD', 'get_ServiceLocator_YdyC4xDService', true],
            'App\\Controller\\VehiculeController::edit' => ['privates', '.service_locator.YdyC4xD', 'get_ServiceLocator_YdyC4xDService', true],
            'App\\Controller\\VehiculeController::index' => ['privates', '.service_locator.y1420Rl', 'get_ServiceLocator_Y1420RlService', true],
            'App\\Controller\\VehiculeController::new' => ['privates', '.service_locator.y1420Rl', 'get_ServiceLocator_Y1420RlService', true],
            'App\\Controller\\VehiculeController::show' => ['privates', '.service_locator.pB20uqv', 'get_ServiceLocator_PB20uqvService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Controller\\ItineraireController:delete' => ['privates', '.service_locator.i7iqqrB', 'get_ServiceLocator_I7iqqrBService', true],
            'App\\Controller\\ItineraireController:edit' => ['privates', '.service_locator.i7iqqrB', 'get_ServiceLocator_I7iqqrBService', true],
            'App\\Controller\\ItineraireController:index' => ['privates', '.service_locator.K9TRytY', 'get_ServiceLocator_K9TRytYService', true],
            'App\\Controller\\ItineraireController:new' => ['privates', '.service_locator.K9TRytY', 'get_ServiceLocator_K9TRytYService', true],
            'App\\Controller\\ItineraireController:show' => ['privates', '.service_locator.FdDxxpr', 'get_ServiceLocator_FdDxxprService', true],
            'App\\Controller\\UtilisateurController:delete' => ['privates', '.service_locator.KzL3gdR', 'get_ServiceLocator_KzL3gdRService', true],
            'App\\Controller\\UtilisateurController:edit' => ['privates', '.service_locator.KzL3gdR', 'get_ServiceLocator_KzL3gdRService', true],
            'App\\Controller\\UtilisateurController:index' => ['privates', '.service_locator.JMejbpE', 'get_ServiceLocator_JMejbpEService', true],
            'App\\Controller\\UtilisateurController:new' => ['privates', '.service_locator.JMejbpE', 'get_ServiceLocator_JMejbpEService', true],
            'App\\Controller\\UtilisateurController:show' => ['privates', '.service_locator.r5W7ygF', 'get_ServiceLocator_R5W7ygFService', true],
            'App\\Controller\\VehiculeController:delete' => ['privates', '.service_locator.YdyC4xD', 'get_ServiceLocator_YdyC4xDService', true],
            'App\\Controller\\VehiculeController:edit' => ['privates', '.service_locator.YdyC4xD', 'get_ServiceLocator_YdyC4xDService', true],
            'App\\Controller\\VehiculeController:index' => ['privates', '.service_locator.y1420Rl', 'get_ServiceLocator_Y1420RlService', true],
            'App\\Controller\\VehiculeController:new' => ['privates', '.service_locator.y1420Rl', 'get_ServiceLocator_Y1420RlService', true],
            'App\\Controller\\VehiculeController:show' => ['privates', '.service_locator.pB20uqv', 'get_ServiceLocator_PB20uqvService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
        ], [
            'App\\Controller\\ItineraireController::delete' => '?',
            'App\\Controller\\ItineraireController::edit' => '?',
            'App\\Controller\\ItineraireController::index' => '?',
            'App\\Controller\\ItineraireController::new' => '?',
            'App\\Controller\\ItineraireController::show' => '?',
            'App\\Controller\\UtilisateurController::delete' => '?',
            'App\\Controller\\UtilisateurController::edit' => '?',
            'App\\Controller\\UtilisateurController::index' => '?',
            'App\\Controller\\UtilisateurController::new' => '?',
            'App\\Controller\\UtilisateurController::show' => '?',
            'App\\Controller\\VehiculeController::delete' => '?',
            'App\\Controller\\VehiculeController::edit' => '?',
            'App\\Controller\\VehiculeController::index' => '?',
            'App\\Controller\\VehiculeController::new' => '?',
            'App\\Controller\\VehiculeController::show' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\ItineraireController:delete' => '?',
            'App\\Controller\\ItineraireController:edit' => '?',
            'App\\Controller\\ItineraireController:index' => '?',
            'App\\Controller\\ItineraireController:new' => '?',
            'App\\Controller\\ItineraireController:show' => '?',
            'App\\Controller\\UtilisateurController:delete' => '?',
            'App\\Controller\\UtilisateurController:edit' => '?',
            'App\\Controller\\UtilisateurController:index' => '?',
            'App\\Controller\\UtilisateurController:new' => '?',
            'App\\Controller\\UtilisateurController:show' => '?',
            'App\\Controller\\VehiculeController:delete' => '?',
            'App\\Controller\\VehiculeController:edit' => '?',
            'App\\Controller\\VehiculeController:index' => '?',
            'App\\Controller\\VehiculeController:new' => '?',
            'App\\Controller\\VehiculeController:show' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
