<?php

namespace Container4ulJDDQ;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAmende2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.Yeu7ARv.App\Entity\Amende' shared service.
     *
     * @return \App\Entity\Amende
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.Yeu7ARv": it references class "App\\Entity\\Amende" but no such service exists.');
    }
}
