<?php

namespace ContainerNRfyAEx;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_D4dgZeaService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.d4dgZea' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.d4dgZea'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\ItineraireController::delete' => ['privates', '.service_locator.i7iqqrB', 'get_ServiceLocator_I7iqqrBService', true],
            'App\\Controller\\ItineraireController::edit' => ['privates', '.service_locator.i7iqqrB', 'get_ServiceLocator_I7iqqrBService', true],
            'App\\Controller\\ItineraireController::index' => ['privates', '.service_locator.K9TRytY', 'get_ServiceLocator_K9TRytYService', true],
            'App\\Controller\\ItineraireController::new' => ['privates', '.service_locator.K9TRytY', 'get_ServiceLocator_K9TRytYService', true],
            'App\\Controller\\ItineraireController::show' => ['privates', '.service_locator.FdDxxpr', 'get_ServiceLocator_FdDxxprService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Controller\\ItineraireController:delete' => ['privates', '.service_locator.i7iqqrB', 'get_ServiceLocator_I7iqqrBService', true],
            'App\\Controller\\ItineraireController:edit' => ['privates', '.service_locator.i7iqqrB', 'get_ServiceLocator_I7iqqrBService', true],
            'App\\Controller\\ItineraireController:index' => ['privates', '.service_locator.K9TRytY', 'get_ServiceLocator_K9TRytYService', true],
            'App\\Controller\\ItineraireController:new' => ['privates', '.service_locator.K9TRytY', 'get_ServiceLocator_K9TRytYService', true],
            'App\\Controller\\ItineraireController:show' => ['privates', '.service_locator.FdDxxpr', 'get_ServiceLocator_FdDxxprService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
        ], [
            'App\\Controller\\ItineraireController::delete' => '?',
            'App\\Controller\\ItineraireController::edit' => '?',
            'App\\Controller\\ItineraireController::index' => '?',
            'App\\Controller\\ItineraireController::new' => '?',
            'App\\Controller\\ItineraireController::show' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\ItineraireController:delete' => '?',
            'App\\Controller\\ItineraireController:edit' => '?',
            'App\\Controller\\ItineraireController:index' => '?',
            'App\\Controller\\ItineraireController:new' => '?',
            'App\\Controller\\ItineraireController:show' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
