<?php

namespace ContainerObJdVxx;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_HzpdFrkService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.HzpdFrk' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.HzpdFrk'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'doctrine' => ['services', 'doctrine', 'getDoctrineService', false],
            'itineraire' => ['privates', '.errored..service_locator.HzpdFrk.App\\Entity\\Itineraire', NULL, 'Cannot autowire service ".service_locator.HzpdFrk": it references class "App\\Entity\\Itineraire" but no such service exists.'],
        ], [
            'doctrine' => '?',
            'itineraire' => 'App\\Entity\\Itineraire',
        ]);
    }
}
