<?php

namespace ContainerRIxxHde;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_FdDxxprService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.FdDxxpr' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.FdDxxpr'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'itineraire' => ['privates', '.errored..service_locator.FdDxxpr.App\\Entity\\Itineraire', NULL, 'Cannot autowire service ".service_locator.FdDxxpr": it references class "App\\Entity\\Itineraire" but no such service exists.'],
        ], [
            'itineraire' => 'App\\Entity\\Itineraire',
        ]);
    }
}
