<?php

namespace Proxies\__CG__\App\Entity;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Reservation extends \App\Entity\Reservation implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Reservation' . "\0" . 'idreservation', '' . "\0" . 'App\\Entity\\Reservation' . "\0" . 'datedebut', '' . "\0" . 'App\\Entity\\Reservation' . "\0" . 'datefin', '' . "\0" . 'App\\Entity\\Reservation' . "\0" . 'status', '' . "\0" . 'App\\Entity\\Reservation' . "\0" . 'prixreservation', '' . "\0" . 'App\\Entity\\Reservation' . "\0" . 'iduser', '' . "\0" . 'App\\Entity\\Reservation' . "\0" . 'idvehicule', '' . "\0" . 'App\\Entity\\Reservation' . "\0" . 'iditineraire'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Reservation' . "\0" . 'idreservation', '' . "\0" . 'App\\Entity\\Reservation' . "\0" . 'datedebut', '' . "\0" . 'App\\Entity\\Reservation' . "\0" . 'datefin', '' . "\0" . 'App\\Entity\\Reservation' . "\0" . 'status', '' . "\0" . 'App\\Entity\\Reservation' . "\0" . 'prixreservation', '' . "\0" . 'App\\Entity\\Reservation' . "\0" . 'iduser', '' . "\0" . 'App\\Entity\\Reservation' . "\0" . 'idvehicule', '' . "\0" . 'App\\Entity\\Reservation' . "\0" . 'iditineraire'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Reservation $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load(): void
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized(): bool
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized): void
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null): void
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer(): ?\Closure
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null): void
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner(): ?\Closure
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties(): array
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getIdreservation(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIdreservation();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdreservation', []);

        return parent::getIdreservation();
    }

    /**
     * {@inheritDoc}
     */
    public function getDatedebut(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDatedebut', []);

        return parent::getDatedebut();
    }

    /**
     * {@inheritDoc}
     */
    public function setDatedebut(\DateTimeInterface $datedebut): \App\Entity\Reservation
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDatedebut', [$datedebut]);

        return parent::setDatedebut($datedebut);
    }

    /**
     * {@inheritDoc}
     */
    public function getDatefin(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDatefin', []);

        return parent::getDatefin();
    }

    /**
     * {@inheritDoc}
     */
    public function setDatefin(\DateTimeInterface $datefin): \App\Entity\Reservation
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDatefin', [$datefin]);

        return parent::setDatefin($datefin);
    }

    /**
     * {@inheritDoc}
     */
    public function getStatus(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStatus', []);

        return parent::getStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function setStatus(string $status): \App\Entity\Reservation
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStatus', [$status]);

        return parent::setStatus($status);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrixreservation(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrixreservation', []);

        return parent::getPrixreservation();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrixreservation(?int $prixreservation): \App\Entity\Reservation
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrixreservation', [$prixreservation]);

        return parent::setPrixreservation($prixreservation);
    }

    /**
     * {@inheritDoc}
     */
    public function getIduser(): ?\App\Entity\Utilisateur
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIduser', []);

        return parent::getIduser();
    }

    /**
     * {@inheritDoc}
     */
    public function setIduser(?\App\Entity\Utilisateur $iduser): \App\Entity\Reservation
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIduser', [$iduser]);

        return parent::setIduser($iduser);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdvehicule(): ?\App\Entity\Vehicule
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdvehicule', []);

        return parent::getIdvehicule();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdvehicule(?\App\Entity\Vehicule $idvehicule): \App\Entity\Reservation
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdvehicule', [$idvehicule]);

        return parent::setIdvehicule($idvehicule);
    }

    /**
     * {@inheritDoc}
     */
    public function getIditineraire(): ?\App\Entity\Itineraire
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIditineraire', []);

        return parent::getIditineraire();
    }

    /**
     * {@inheritDoc}
     */
    public function setIditineraire(?\App\Entity\Itineraire $iditineraire): \App\Entity\Reservation
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIditineraire', [$iditineraire]);

        return parent::setIditineraire($iditineraire);
    }

}
