<?php

namespace ContainerS5qyPfw;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_HoFxxtService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ho_fxxt' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ho_fxxt'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'ratingRepository' => ['privates', 'App\\Repository\\RatingRepository', 'getRatingRepositoryService', true],
        ], [
            'ratingRepository' => 'App\\Repository\\RatingRepository',
        ]);
    }
}
