<?php

namespace ContainerYmhCpYz;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAffectationbadgeRepositoryService extends App_KernelDevContainer
{
    /*
     * Gets the private 'App\Repository\AffectationbadgeRepository' shared autowired service.
     *
     * @return \App\Repository\AffectationbadgeRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\AffectationbadgeRepository'] = new \App\Repository\AffectationbadgeRepository(($container->services['doctrine'] ?? $container->getDoctrineService()));
    }
}
