<?php

namespace ContainerYmhCpYz;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getItineraireControllerService extends App_KernelDevContainer
{
    /*
     * Gets the public 'App\Controller\ItineraireController' shared autowired service.
     *
     * @return \App\Controller\ItineraireController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\ItineraireController'] = $instance = new \App\Controller\ItineraireController();

        $instance->setContainer(($container->privates['.service_locator.mx0UMmY'] ?? $container->load('get_ServiceLocator_Mx0UMmYService'))->withContext('App\\Controller\\ItineraireController', $container));

        return $instance;
    }
}
