<?php

namespace ContainerYmhCpYz;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getParkControllerService extends App_KernelDevContainer
{
    /*
     * Gets the public 'App\Controller\ParkController' shared autowired service.
     *
     * @return \App\Controller\ParkController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\ParkController'] = $instance = new \App\Controller\ParkController();

        $instance->setContainer(($container->privates['.service_locator.mx0UMmY'] ?? $container->load('get_ServiceLocator_Mx0UMmYService'))->withContext('App\\Controller\\ParkController', $container));

        return $instance;
    }
}
