<?php

namespace ContainerYmhCpYz;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getParkTypeService extends App_KernelDevContainer
{
    /*
     * Gets the private 'App\Form\ParkType' shared autowired service.
     *
     * @return \App\Form\ParkType
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Form\\ParkType'] = new \App\Form\ParkType();
    }
}
