<?php

namespace ContainerYmhCpYz;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUtilisateur1TypeService extends App_KernelDevContainer
{
    /*
     * Gets the private 'App\Form\Utilisateur1Type' shared autowired service.
     *
     * @return \App\Form\Utilisateur1Type
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Form\\Utilisateur1Type'] = new \App\Form\Utilisateur1Type();
    }
}
