<?php

<<<<<<<< HEAD:var/cache/dev/ContainerBR6n7jk/getBadgeService.php
namespace ContainerBR6n7jk;

========
namespace ContainerXxRwAvm;
>>>>>>>> dafaa418e965cb562724709fb7ac21731436e887:var/cache/dev/ContainerXxRwAvm/getBadgeService.php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBadgeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.6DFA8px.App\Entity\Badge' shared service.
     *
     * @return \App\Entity\Badge
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.6DFA8px": it references class "App\\Entity\\Badge" but no such service exists.');
    }
}
