<?php

<<<<<<<< HEAD:var/cache/dev/ContainerBR6n7jk/getItineraire2Service.php
namespace ContainerBR6n7jk;

========
namespace ContainerXxRwAvm;
>>>>>>>> dafaa418e965cb562724709fb7ac21731436e887:var/cache/dev/ContainerXxRwAvm/getItineraire2Service.php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getItineraire2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.WIErbLc.App\Entity\Itineraire' shared service.
     *
     * @return \App\Entity\Itineraire
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.WIErbLc": it references class "App\\Entity\\Itineraire" but no such service exists.');
    }
}
