<?php

<<<<<<<< HEAD:var/cache/dev/ContainerBR6n7jk/getPark3Service.php
namespace ContainerBR6n7jk;

========
namespace ContainerXxRwAvm;
>>>>>>>> dafaa418e965cb562724709fb7ac21731436e887:var/cache/dev/ContainerXxRwAvm/getPark2Service.php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPark3Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.GxLEY6J.App\Entity\Park' shared service.
     *
     * @return \App\Entity\Park
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.GxLEY6J": it references class "App\\Entity\\Park" but no such service exists.');
    }
}
