<?php

namespace ContainerFfxB5hV;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Fo9YP3Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.fo9_yP3' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.fo9_yP3'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'passwordHasher' => ['privates', '.errored.2Gi.y3Y', NULL, 'Cannot determine controller argument for "App\\Controller\\LoginController::login()": the $passwordHasher argument is type-hinted with the non-existent class or interface: "Symfony\\Component\\Security\\Core\\Encoder\\UserPasswordHasherInterface".'],
        ], [
            'passwordHasher' => '?',
        ]);
    }
}
