<?php

namespace ContainerFfxB5hV;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored_2Gi_Y3YService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored.2Gi.y3Y' shared service.
     *
     * @return \Symfony\Component\Security\Core\Encoder\UserPasswordHasherInterface
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot determine controller argument for "App\\Controller\\LoginController::login()": the $passwordHasher argument is type-hinted with the non-existent class or interface: "Symfony\\Component\\Security\\Core\\Encoder\\UserPasswordHasherInterface".');
    }
}
