<?php

namespace ContainerEW8Jxv5;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_I687sDcService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.I687sDc' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.I687sDc'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\ItineraireController::delete' => ['privates', '.service_locator.WIErbLc', 'get_ServiceLocator_WIErbLcService', true],
            'App\\Controller\\ItineraireController::edit' => ['privates', '.service_locator.WIErbLc', 'get_ServiceLocator_WIErbLcService', true],
            'App\\Controller\\ItineraireController::index' => ['privates', '.service_locator.UnRSzoY', 'get_ServiceLocator_UnRSzoYService', true],
            'App\\Controller\\ItineraireController::new' => ['privates', '.service_locator.UnRSzoY', 'get_ServiceLocator_UnRSzoYService', true],
            'App\\Controller\\ItineraireController::show' => ['privates', '.service_locator.OT94dsS', 'get_ServiceLocator_OT94dsSService', true],
            'App\\Controller\\UtilisateurController::delete' => ['privates', '.service_locator.Rp1teHo', 'get_ServiceLocator_Rp1teHoService', true],
            'App\\Controller\\UtilisateurController::edit' => ['privates', '.service_locator.Rp1teHo', 'get_ServiceLocator_Rp1teHoService', true],
            'App\\Controller\\UtilisateurController::index' => ['privates', '.service_locator.b7IruXu', 'get_ServiceLocator_B7IruXuService', true],
            'App\\Controller\\UtilisateurController::new' => ['privates', '.service_locator.b7IruXu', 'get_ServiceLocator_B7IruXuService', true],
            'App\\Controller\\UtilisateurController::show' => ['privates', '.service_locator.wxsJsLA', 'get_ServiceLocator_WxsJsLAService', true],
            'App\\Controller\\VehiculeController::delete' => ['privates', '.service_locator.2HWUMMh', 'get_ServiceLocator_2HWUMMhService', true],
            'App\\Controller\\VehiculeController::edit' => ['privates', '.service_locator.2HWUMMh', 'get_ServiceLocator_2HWUMMhService', true],
            'App\\Controller\\VehiculeController::index' => ['privates', '.service_locator.4SqQ2.V', 'get_ServiceLocator_4SqQ2_VService', true],
            'App\\Controller\\VehiculeController::new' => ['privates', '.service_locator.4SqQ2.V', 'get_ServiceLocator_4SqQ2_VService', true],
            'App\\Controller\\VehiculeController::show' => ['privates', '.service_locator.0J1782j', 'get_ServiceLocator_0J1782jService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Controller\\ItineraireController:delete' => ['privates', '.service_locator.WIErbLc', 'get_ServiceLocator_WIErbLcService', true],
            'App\\Controller\\ItineraireController:edit' => ['privates', '.service_locator.WIErbLc', 'get_ServiceLocator_WIErbLcService', true],
            'App\\Controller\\ItineraireController:index' => ['privates', '.service_locator.UnRSzoY', 'get_ServiceLocator_UnRSzoYService', true],
            'App\\Controller\\ItineraireController:new' => ['privates', '.service_locator.UnRSzoY', 'get_ServiceLocator_UnRSzoYService', true],
            'App\\Controller\\ItineraireController:show' => ['privates', '.service_locator.OT94dsS', 'get_ServiceLocator_OT94dsSService', true],
            'App\\Controller\\UtilisateurController:delete' => ['privates', '.service_locator.Rp1teHo', 'get_ServiceLocator_Rp1teHoService', true],
            'App\\Controller\\UtilisateurController:edit' => ['privates', '.service_locator.Rp1teHo', 'get_ServiceLocator_Rp1teHoService', true],
            'App\\Controller\\UtilisateurController:index' => ['privates', '.service_locator.b7IruXu', 'get_ServiceLocator_B7IruXuService', true],
            'App\\Controller\\UtilisateurController:new' => ['privates', '.service_locator.b7IruXu', 'get_ServiceLocator_B7IruXuService', true],
            'App\\Controller\\UtilisateurController:show' => ['privates', '.service_locator.wxsJsLA', 'get_ServiceLocator_WxsJsLAService', true],
            'App\\Controller\\VehiculeController:delete' => ['privates', '.service_locator.2HWUMMh', 'get_ServiceLocator_2HWUMMhService', true],
            'App\\Controller\\VehiculeController:edit' => ['privates', '.service_locator.2HWUMMh', 'get_ServiceLocator_2HWUMMhService', true],
            'App\\Controller\\VehiculeController:index' => ['privates', '.service_locator.4SqQ2.V', 'get_ServiceLocator_4SqQ2_VService', true],
            'App\\Controller\\VehiculeController:new' => ['privates', '.service_locator.4SqQ2.V', 'get_ServiceLocator_4SqQ2_VService', true],
            'App\\Controller\\VehiculeController:show' => ['privates', '.service_locator.0J1782j', 'get_ServiceLocator_0J1782jService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
        ], [
            'App\\Controller\\ItineraireController::delete' => '?',
            'App\\Controller\\ItineraireController::edit' => '?',
            'App\\Controller\\ItineraireController::index' => '?',
            'App\\Controller\\ItineraireController::new' => '?',
            'App\\Controller\\ItineraireController::show' => '?',
            'App\\Controller\\UtilisateurController::delete' => '?',
            'App\\Controller\\UtilisateurController::edit' => '?',
            'App\\Controller\\UtilisateurController::index' => '?',
            'App\\Controller\\UtilisateurController::new' => '?',
            'App\\Controller\\UtilisateurController::show' => '?',
            'App\\Controller\\VehiculeController::delete' => '?',
            'App\\Controller\\VehiculeController::edit' => '?',
            'App\\Controller\\VehiculeController::index' => '?',
            'App\\Controller\\VehiculeController::new' => '?',
            'App\\Controller\\VehiculeController::show' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\ItineraireController:delete' => '?',
            'App\\Controller\\ItineraireController:edit' => '?',
            'App\\Controller\\ItineraireController:index' => '?',
            'App\\Controller\\ItineraireController:new' => '?',
            'App\\Controller\\ItineraireController:show' => '?',
            'App\\Controller\\UtilisateurController:delete' => '?',
            'App\\Controller\\UtilisateurController:edit' => '?',
            'App\\Controller\\UtilisateurController:index' => '?',
            'App\\Controller\\UtilisateurController:new' => '?',
            'App\\Controller\\UtilisateurController:show' => '?',
            'App\\Controller\\VehiculeController:delete' => '?',
            'App\\Controller\\VehiculeController:edit' => '?',
            'App\\Controller\\VehiculeController:index' => '?',
            'App\\Controller\\VehiculeController:new' => '?',
            'App\\Controller\\VehiculeController:show' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
