<?php

<<<<<<<< Updated upstream:var/cache/dev/ContainerQnMZChq/getVehiculeService.php
namespace ContainerQnMZChq;
========
namespace ContainerEW8Jxv5;
>>>>>>>> Stashed changes:var/cache/dev/ContainerEW8Jxv5/getVehiculeService.php


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getVehiculeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.0J1782j.App\Entity\Vehicule' shared service.
     *
     * @return \App\Entity\Vehicule
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.0J1782j": it references class "App\\Entity\\Vehicule" but no such service exists.');
    }
}
