<?php

namespace ContainerO3vAJ2y;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getOneupUploader_ChunkManagerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'oneup_uploader.chunk_manager' shared service.
     *
     * @return \Oneup\UploaderBundle\Uploader\Chunk\ChunkManager
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'oneup'.\DIRECTORY_SEPARATOR.'uploader-bundle'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Uploader'.\DIRECTORY_SEPARATOR.'Chunk'.\DIRECTORY_SEPARATOR.'ChunkManagerInterface.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'oneup'.\DIRECTORY_SEPARATOR.'uploader-bundle'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Uploader'.\DIRECTORY_SEPARATOR.'Chunk'.\DIRECTORY_SEPARATOR.'ChunkManager.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'oneup'.\DIRECTORY_SEPARATOR.'uploader-bundle'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Uploader'.\DIRECTORY_SEPARATOR.'Chunk'.\DIRECTORY_SEPARATOR.'Storage'.\DIRECTORY_SEPARATOR.'ChunkStorageInterface.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'oneup'.\DIRECTORY_SEPARATOR.'uploader-bundle'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Uploader'.\DIRECTORY_SEPARATOR.'Chunk'.\DIRECTORY_SEPARATOR.'Storage'.\DIRECTORY_SEPARATOR.'FilesystemStorage.php';

        return $container->services['oneup_uploader.chunk_manager'] = new \Oneup\UploaderBundle\Uploader\Chunk\ChunkManager($container->getParameter('oneup_uploader.chunks'), new \Oneup\UploaderBundle\Uploader\Chunk\Storage\FilesystemStorage(($container->targetDir.''.'/uploader/chunks')));
    }
}
