<?php

namespace ContainerSaoww6i;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Eu__KmpService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.eu..Kmp' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.eu..Kmp'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'utilisateur' => ['privates', '.errored..service_locator.eu..Kmp.App\\Entity\\Utilisateur', NULL, 'Cannot autowire service ".service_locator.eu..Kmp": it references class "App\\Entity\\Utilisateur" but no such service exists.'],
            'utilisateurRepository' => ['privates', 'App\\Repository\\UtilisateurRepository', 'getUtilisateurRepositoryService', true],
        ], [
            'entityManager' => '?',
            'utilisateur' => 'App\\Entity\\Utilisateur',
            'utilisateurRepository' => 'App\\Repository\\UtilisateurRepository',
        ]);
    }
}
