<?php

namespace ContainerSaoww6i;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_FNVMkHCService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.fNVMkHC' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.fNVMkHC'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'serializer' => ['services', '.container.private.serializer', 'get_Container_Private_SerializerService', true],
            'vehicule' => ['privates', '.errored..service_locator.fNVMkHC.App\\Entity\\Vehicule', NULL, 'Cannot autowire service ".service_locator.fNVMkHC": it references class "App\\Entity\\Vehicule" but no such service exists.'],
            'vehiculeRepository' => ['privates', 'App\\Repository\\VehiculeRepository', 'getVehiculeRepositoryService', true],
        ], [
            'serializer' => '?',
            'vehicule' => 'App\\Entity\\Vehicule',
            'vehiculeRepository' => 'App\\Repository\\VehiculeRepository',
        ]);
    }
}
