<?php

<<<<<<<< HEAD:var/cache/dev/ContainerBuxymzH/get_ServiceLocator_Ho9aMJBService.php
namespace ContainerBuxymzH;

========
namespace ContainerCVw8QWF;
>>>>>>>> 471308da4104360eaaad4f70dbeadb16addb5ea7:var/cache/dev/ContainerCVw8QWF/get_ServiceLocator_QXFbo8_Service.php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_QXFbo8_Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.QXFbo8.' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.QXFbo8.'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'badge' => ['privates', '.errored..service_locator.QXFbo8..App\\Entity\\Badge', NULL, 'Cannot autowire service ".service_locator.QXFbo8.": it references class "App\\Entity\\Badge" but no such service exists.'],
        ], [
            'badge' => 'App\\Entity\\Badge',
        ]);
    }
}
