<?php

<<<<<<<< HEAD:var/cache/dev/ContainerBuxymzH/get_ServiceLocator_ZNVBNHvService.php
namespace ContainerBuxymzH;

========
namespace ContainerCVw8QWF;
>>>>>>>> 471308da4104360eaaad4f70dbeadb16addb5ea7:var/cache/dev/ContainerCVw8QWF/get_ServiceLocator_CGoyxgZService.php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_CGoyxgZService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.cGoyxgZ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.cGoyxgZ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'park' => ['privates', '.errored..service_locator.cGoyxgZ.App\\Entity\\Park', NULL, 'Cannot autowire service ".service_locator.cGoyxgZ": it references class "App\\Entity\\Park" but no such service exists.'],
            'parkRepository' => ['privates', 'App\\Repository\\ParkRepository', 'getParkRepositoryService', true],
        ], [
            'park' => 'App\\Entity\\Park',
            'parkRepository' => 'App\\Repository\\ParkRepository',
        ]);
    }
}
