<?php

<<<<<<<< HEAD:var/cache/dev/ContainerBuxymzH/get_ServiceLocator_1ZBJPocService.php
namespace ContainerBuxymzH;

========
namespace ContainerCVw8QWF;
>>>>>>>> 471308da4104360eaaad4f70dbeadb16addb5ea7:var/cache/dev/ContainerCVw8QWF/get_ServiceLocator_OAbCvMmService.php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_OAbCvMmService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.oAbCvMm' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.oAbCvMm'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'historique' => ['privates', '.errored..service_locator.oAbCvMm.App\\Entity\\Historique', NULL, 'Cannot autowire service ".service_locator.oAbCvMm": it references class "App\\Entity\\Historique" but no such service exists.'],
        ], [
            'historique' => 'App\\Entity\\Historique',
        ]);
    }
}
