<?php

<<<<<<<< HEAD:var/cache/dev/ContainerBuxymzH/get_ServiceLocator_K9TRytYService.php
namespace ContainerBuxymzH;

========
namespace ContainerCVw8QWF;
>>>>>>>> 471308da4104360eaaad4f70dbeadb16addb5ea7:var/cache/dev/ContainerCVw8QWF/get_ServiceLocator_UnRSzoYService.php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_UnRSzoYService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.UnRSzoY' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.UnRSzoY'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'itineraireRepository' => ['privates', 'App\\Repository\\ItineraireRepository', 'getItineraireRepositoryService', true],
        ], [
            'itineraireRepository' => 'App\\Repository\\ItineraireRepository',
        ]);
    }
}
