<?php

<<<<<<<< HEAD:var/cache/dev/ContainerBuxymzH/getHistorique2Service.php
namespace ContainerBuxymzH;

========
namespace ContainerCVw8QWF;
>>>>>>>> 471308da4104360eaaad4f70dbeadb16addb5ea7:var/cache/dev/ContainerCVw8QWF/getHistorique2Service.php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getHistorique2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.qx3nh5Y.App\Entity\Historique' shared service.
     *
     * @return \App\Entity\Historique
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.qx3nh5Y": it references class "App\\Entity\\Historique" but no such service exists.');
    }
}
