<?php

<<<<<<<< HEAD:var/cache/dev/ContainerBuxymzH/getItineraireService.php
namespace ContainerBuxymzH;

========
namespace ContainerCVw8QWF;
>>>>>>>> 471308da4104360eaaad4f70dbeadb16addb5ea7:var/cache/dev/ContainerCVw8QWF/getItineraireService.php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getItineraireService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.OT94dsS.App\Entity\Itineraire' shared service.
     *
     * @return \App\Entity\Itineraire
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.OT94dsS": it references class "App\\Entity\\Itineraire" but no such service exists.');
    }
}
