<?php

<<<<<<<< HEAD:var/cache/dev/ContainerBuxymzH/getParkService.php
namespace ContainerBuxymzH;

========
namespace ContainerCVw8QWF;
>>>>>>>> 471308da4104360eaaad4f70dbeadb16addb5ea7:var/cache/dev/ContainerCVw8QWF/getParkService.php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getParkService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.._4ytyw.App\Entity\Park' shared service.
     *
     * @return \App\Entity\Park
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.._4ytyw": it references class "App\\Entity\\Park" but no such service exists.');
    }
}
