<?php

<<<<<<<< HEAD:var/cache/dev/ContainerBuxymzH/getPark2Service.php
namespace ContainerBuxymzH;

========
namespace ContainerCVw8QWF;
>>>>>>>> 471308da4104360eaaad4f70dbeadb16addb5ea7:var/cache/dev/ContainerCVw8QWF/getPark2Service.php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPark2Service extends App_KernelDevDebugContainer
{
    /**
<<<<<<<< HEAD:var/cache/dev/ContainerBuxymzH/getPark2Service.php
     * Gets the private '.errored..service_locator.dUBUwhu.App\Entity\Park' shared service.
========
     * Gets the private '.errored..service_locator.GxLEY6J.App\Entity\Park' shared service.
>>>>>>>> 471308da4104360eaaad4f70dbeadb16addb5ea7:var/cache/dev/ContainerCVw8QWF/getPark2Service.php
     *
     * @return \App\Entity\Park
     */
    public static function do($container, $lazyLoad = true)
    {
<<<<<<<< HEAD:var/cache/dev/ContainerBuxymzH/getPark2Service.php
        $container->throw('Cannot autowire service ".service_locator.dUBUwhu": it references class "App\\Entity\\Park" but no such service exists.');
========
        $container->throw('Cannot autowire service ".service_locator.GxLEY6J": it references class "App\\Entity\\Park" but no such service exists.');
>>>>>>>> 471308da4104360eaaad4f70dbeadb16addb5ea7:var/cache/dev/ContainerCVw8QWF/getPark2Service.php
    }
}
