<?php

<<<<<<<< HEAD:var/cache/dev/ContainerBuxymzH/getReservation2Service.php
namespace ContainerBuxymzH;

========
namespace ContainerCVw8QWF;
>>>>>>>> 471308da4104360eaaad4f70dbeadb16addb5ea7:var/cache/dev/ContainerCVw8QWF/getReservation2Service.php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getReservation2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.EdH9l1X.App\Entity\Reservation' shared service.
     *
     * @return \App\Entity\Reservation
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.EdH9l1X": it references class "App\\Entity\\Reservation" but no such service exists.');
    }
}
