<?php

<<<<<<<< HEAD:var/cache/dev/ContainerBuxymzH/getUtilisateur2Service.php
namespace ContainerBuxymzH;

========
namespace ContainerCVw8QWF;
>>>>>>>> 471308da4104360eaaad4f70dbeadb16addb5ea7:var/cache/dev/ContainerCVw8QWF/getUtilisateur2Service.php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUtilisateur2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.wxsJsLA.App\Entity\Utilisateur' shared service.
     *
     * @return \App\Entity\Utilisateur
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.wxsJsLA": it references class "App\\Entity\\Utilisateur" but no such service exists.');
    }
}
