<?php

<<<<<<<< HEAD:var/cache/dev/ContainerBuxymzH/getVehicule2Service.php
namespace ContainerBuxymzH;

========
namespace ContainerCVw8QWF;
>>>>>>>> 471308da4104360eaaad4f70dbeadb16addb5ea7:var/cache/dev/ContainerCVw8QWF/getVehicule2Service.php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getVehicule2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.2HWUMMh.App\Entity\Vehicule' shared service.
     *
     * @return \App\Entity\Vehicule
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.2HWUMMh": it references class "App\\Entity\\Vehicule" but no such service exists.');
    }
}
