<?php

<<<<<<<< Updated upstream:var/cache/dev/Container32wZr7w/get_ServiceLocator_4SqQ2_VService.php
namespace Container32wZr7w;
========
namespace ContainerL7ax9pe;
>>>>>>>> Stashed changes:var/cache/dev/ContainerL7ax9pe/get_ServiceLocator_Y1420RlService.php


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Y1420RlService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.y1420Rl' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.y1420Rl'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'vehiculeRepository' => ['privates', 'App\\Repository\\VehiculeRepository', 'getVehiculeRepositoryService', true],
        ], [
            'vehiculeRepository' => 'App\\Repository\\VehiculeRepository',
        ]);
    }
}
