<?php

<<<<<<<< Updated upstream:var/cache/dev/Container3Nju3es/getBadgeService.php
<<<<<<<< Updated upstream:var/cache/dev/ContainerXxRwAvm/getBadgeService.php
namespace ContainerXxRwAvm;
========
namespace Container3Nju3es;

>>>>>>>> Stashed changes:var/cache/dev/Container3Nju3es/getBadgeService.php
========
namespace ContainerL7ax9pe;

>>>>>>>> Stashed changes:var/cache/dev/ContainerL7ax9pe/getBadgeService.php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBadgeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.20cMmfJ.App\Entity\Badge' shared service.
     *
     * @return \App\Entity\Badge
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.20cMmfJ": it references class "App\\Entity\\Badge" but no such service exists.');
    }
}
