<?php

<<<<<<<< Updated upstream:var/cache/dev/Container3Nju3es/getItineraire2Service.php
<<<<<<<< Updated upstream:var/cache/dev/ContainerXxRwAvm/getItineraire2Service.php
namespace ContainerXxRwAvm;
========
namespace Container3Nju3es;

>>>>>>>> Stashed changes:var/cache/dev/Container3Nju3es/getItineraire2Service.php
========
namespace ContainerL7ax9pe;

>>>>>>>> Stashed changes:var/cache/dev/ContainerL7ax9pe/getItineraire2Service.php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getItineraire2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.i7iqqrB.App\Entity\Itineraire' shared service.
     *
     * @return \App\Entity\Itineraire
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.i7iqqrB": it references class "App\\Entity\\Itineraire" but no such service exists.');
    }
}
