<?php

<<<<<<<< Updated upstream:var/cache/dev/ContainerXrI0aMK/getPark3Service.php
namespace ContainerXrI0aMK;
========
namespace ContainerL7ax9pe;
>>>>>>>> Stashed changes:var/cache/dev/ContainerL7ax9pe/getPark3Service.php


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPark3Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.tUog_7F.App\Entity\Park' shared service.
     *
     * @return \App\Entity\Park
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.tUog_7F": it references class "App\\Entity\\Park" but no such service exists.');
    }
}
