<?php

<<<<<<<< Updated upstream:var/cache/dev/ContainerS5qyPfw/getReclamationService.php
namespace ContainerS5qyPfw;
========
namespace ContainerL7ax9pe;
>>>>>>>> Stashed changes:var/cache/dev/ContainerL7ax9pe/getReclamationService.php


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getReclamationService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.i7JOFAN.App\Entity\Reclamation' shared service.
     *
     * @return \App\Entity\Reclamation
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.i7JOFAN": it references class "App\\Entity\\Reclamation" but no such service exists.');
    }
}
