<?php

<<<<<<<< HEAD:var/cache/dev/ContainerBR6n7jk/get_ServiceLocator_FdDxxprService.php
namespace ContainerBR6n7jk;

========
namespace ContainerXxRwAvm;
>>>>>>>> dafaa418e965cb562724709fb7ac21731436e887:var/cache/dev/ContainerXxRwAvm/get_ServiceLocator_OT94dsSService.php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_OT94dsSService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.OT94dsS' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.OT94dsS'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'itineraire' => ['privates', '.errored..service_locator.OT94dsS.App\\Entity\\Itineraire', NULL, 'Cannot autowire service ".service_locator.OT94dsS": it references class "App\\Entity\\Itineraire" but no such service exists.'],
        ], [
            'itineraire' => 'App\\Entity\\Itineraire',
        ]);
    }
}
