<?php

<<<<<<<< HEAD:var/cache/dev/ContainerBR6n7jk/getUtilisateurService.php
namespace ContainerBR6n7jk;

========
namespace ContainerXxRwAvm;
>>>>>>>> dafaa418e965cb562724709fb7ac21731436e887:var/cache/dev/ContainerXxRwAvm/getUtilisateurService.php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUtilisateurService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.Rp1teHo.App\Entity\Utilisateur' shared service.
     *
     * @return \App\Entity\Utilisateur
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.Rp1teHo": it references class "App\\Entity\\Utilisateur" but no such service exists.');
    }
}
