<?php

namespace ContainerDWdRG4Z;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_RFPsOlfService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.rFPsOlf' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.rFPsOlf'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'utilisateurRepository' => ['privates', '.errored.Q9XhN5B', NULL, 'Cannot determine controller argument for "App\\Controller\\RegisterController::register()": the $utilisateurRepository argument is type-hinted with the non-existent class or interface: "App\\Controller\\UtilisateurRepository". Did you forget to add a use statement?'],
        ], [
            'utilisateurRepository' => '?',
        ]);
    }
}
