<?php

namespace ContainerDWdRG4Z;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored_Q9XhN5BService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored.Q9XhN5B' shared service.
     *
     * @return \App\Controller\UtilisateurRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot determine controller argument for "App\\Controller\\RegisterController::register()": the $utilisateurRepository argument is type-hinted with the non-existent class or interface: "App\\Controller\\UtilisateurRepository". Did you forget to add a use statement?');
    }
}
