<?php

namespace ContainerDWdRG4Z;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPark2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.dUBUwhu.App\Entity\Park' shared service.
     *
     * @return \App\Entity\Park
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.dUBUwhu": it references class "App\\Entity\\Park" but no such service exists.');
    }
}
