<?php

<<<<<<<< Updated upstream:var/cache/dev/ContainerEW8Jxv5/get_ServiceLocator_Y4J_A_EService.php
<<<<<<<< Updated upstream:var/cache/dev/ContainerQnMZChq/get_ServiceLocator_Y4J_A_EService.php
namespace ContainerQnMZChq;
========
namespace ContainerEW8Jxv5;
>>>>>>>> Stashed changes:var/cache/dev/ContainerEW8Jxv5/get_ServiceLocator_Y4J_A_EService.php
========
namespace ContainerGrzg32x;
>>>>>>>> Stashed changes:var/cache/dev/ContainerGrzg32x/get_ServiceLocator_VddRp04Service.php


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_VddRp04Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.VddRp04' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.VddRp04'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'reservationRepository' => ['privates', 'App\\Repository\\ReservationRepository', 'getReservationRepositoryService', true],
        ], [
            'reservationRepository' => 'App\\Repository\\ReservationRepository',
        ]);
    }
}
