<?php

<<<<<<<< Updated upstream:var/cache/dev/ContainerLoBRsC4/getItineraireControllerService.php
namespace ContainerLoBRsC4;
========
namespace ContainerGrzg32x;
>>>>>>>> Stashed changes:var/cache/dev/ContainerGrzg32x/getHistoriqueControllerService.php


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getHistoriqueControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\HistoriqueController' shared autowired service.
     *
     * @return \App\Controller\HistoriqueController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'framework-bundle'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'AbstractController.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'HistoriqueController.php';

        $container->services['App\\Controller\\HistoriqueController'] = $instance = new \App\Controller\HistoriqueController();

<<<<<<<< Updated upstream:var/cache/dev/ContainerLoBRsC4/getItineraireControllerService.php
        $instance->setContainer(($container->privates['.service_locator.mx0UMmY'] ?? $container->load('get_ServiceLocator_Mx0UMmYService'))->withContext('App\\Controller\\ItineraireController', $container));
========
        $instance->setContainer(($container->privates['.service_locator.mx0UMmY'] ?? $container->load('get_ServiceLocator_Mx0UMmYService'))->withContext('App\\Controller\\HistoriqueController', $container));
>>>>>>>> Stashed changes:var/cache/dev/ContainerGrzg32x/getHistoriqueControllerService.php

        return $instance;
    }
}
