<?php

<<<<<<<< Updated upstream:var/cache/dev/ContainerEW8Jxv5/getItineraire2Service.php
<<<<<<<< Updated upstream:var/cache/dev/ContainerQnMZChq/getItineraire2Service.php
namespace ContainerQnMZChq;
========
namespace ContainerEW8Jxv5;
>>>>>>>> Stashed changes:var/cache/dev/ContainerEW8Jxv5/getItineraire2Service.php
========
namespace ContainerGrzg32x;
>>>>>>>> Stashed changes:var/cache/dev/ContainerGrzg32x/getHistorique2Service.php


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getHistorique2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.7u.gGMd.App\Entity\Historique' shared service.
     *
     * @return \App\Entity\Historique
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.7u.gGMd": it references class "App\\Entity\\Historique" but no such service exists.');
    }
}
