<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYmhCpYz\App_KernelDevContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYmhCpYz/App_KernelDevContainer.php') {
    touch(__DIR__.'/ContainerYmhCpYz.legacy');

    return;
}

if (!\class_exists(App_KernelDevContainer::class, false)) {
    \class_alias(\ContainerYmhCpYz\App_KernelDevContainer::class, App_KernelDevContainer::class, false);
}

return new \ContainerYmhCpYz\App_KernelDevContainer([
    'container.build_hash' => 'YmhCpYz',
    'container.build_id' => '2981686c',
    'container.build_time' => 1680224025,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerYmhCpYz');
