<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPx1g6qe\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPx1g6qe/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerPx1g6qe.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerPx1g6qe\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerPx1g6qe\App_KernelDevDebugContainer([
    'container.build_hash' => 'Px1g6qe',
    'container.build_id' => '59da2455',
    'container.build_time' => 1680223209,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPx1g6qe');
