<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

<<<<<<< Updated upstream
<<<<<<< HEAD
if (\class_exists(\ContainerBuxymzH\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBuxymzH/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerBuxymzH.legacy');
=======
if (\class_exists(\ContainerXxRwAvm\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXxRwAvm/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXxRwAvm.legacy');
>>>>>>> 471308da4104360eaaad4f70dbeadb16addb5ea7
=======
if (\class_exists(\Container3Nju3es\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container3Nju3es/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container3Nju3es.legacy');
>>>>>>> Stashed changes

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
<<<<<<< Updated upstream
<<<<<<< HEAD
    \class_alias(\ContainerBuxymzH\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerBuxymzH\App_KernelDevDebugContainer([
    'container.build_hash' => 'BuxymzH',
    'container.build_id' => '85687c03',
    'container.build_time' => 1681179147,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerBuxymzH');
=======
    \class_alias(\ContainerXxRwAvm\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXxRwAvm\App_KernelDevDebugContainer([
    'container.build_hash' => 'XxRwAvm',
    'container.build_id' => '2cd418a0',
    'container.build_time' => 1681174748,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXxRwAvm');
>>>>>>> 471308da4104360eaaad4f70dbeadb16addb5ea7
=======
    \class_alias(\Container3Nju3es\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container3Nju3es\App_KernelDevDebugContainer([
    'container.build_hash' => '3Nju3es',
    'container.build_id' => '93e18e50',
    'container.build_time' => 1681124200,
], __DIR__.\DIRECTORY_SEPARATOR.'Container3Nju3es');
>>>>>>> Stashed changes
