<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYTXpmtg\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYTXpmtg/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerYTXpmtg.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerYTXpmtg\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerYTXpmtg\App_KernelDevDebugContainer([
    'container.build_hash' => 'YTXpmtg',
    'container.build_id' => '45ea7180',
    'container.build_time' => 1682461505,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerYTXpmtg');
