<?php

namespace ContainerXmUnInr;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored_PqnzereService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored.pqnzere' shared service.
     *
     * @return \App\Respository\ReservationRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot determine controller argument for "App\\Controller\\HistoriqueController::index2()": the $reservationRepository argument is type-hinted with the non-existent class or interface: "App\\Respository\\ReservationRepository".');
    }
}
