<?php

namespace ContainerXmUnInr;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_DDViQaIService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.dDViQaI' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.dDViQaI'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'historiqueRepository' => ['privates', 'App\\Repository\\HistoriqueRepository', 'getHistoriqueRepositoryService', true],
            'reservationRepository' => ['privates', '.errored.pqnzere', NULL, 'Cannot determine controller argument for "App\\Controller\\HistoriqueController::index2()": the $reservationRepository argument is type-hinted with the non-existent class or interface: "App\\Respository\\ReservationRepository".'],
        ], [
            'historiqueRepository' => 'App\\Repository\\HistoriqueRepository',
            'reservationRepository' => '?',
        ]);
    }
}
