<?php

<<<<<<<< Updated upstream:var/cache/dev/ContainerS5qyPfw/get_ServiceLocator_DioyBFPService.php
namespace ContainerS5qyPfw;
========
namespace ContainerXmUnInr;
>>>>>>>> Stashed changes:var/cache/dev/ContainerXmUnInr/get_ServiceLocator_EkDI47jService.php


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_DioyBFPService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.dioyBFP' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.dioyBFP'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'repo' => ['privates', 'App\\Repository\\BadgeRepository', 'getBadgeRepositoryService', true],
        ], [
            'repo' => 'App\\Repository\\BadgeRepository',
        ]);
    }
}
