<?php

<<<<<<<< Updated upstream:var/cache/dev/Container32wZr7w/getBadge2Service.php
namespace Container32wZr7w;
========
namespace ContainerXmUnInr;
>>>>>>>> Stashed changes:var/cache/dev/ContainerXmUnInr/getBadge2Service.php


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBadge2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.QXFbo8..App\Entity\Badge' shared service.
     *
     * @return \App\Entity\Badge
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.QXFbo8.": it references class "App\\Entity\\Badge" but no such service exists.');
    }
}
