<?php

<<<<<<<< Updated upstream:var/cache/dev/Container32wZr7w/getItineraire2Service.php
namespace Container32wZr7w;
========
namespace ContainerXmUnInr;
>>>>>>>> Stashed changes:var/cache/dev/ContainerXmUnInr/getItineraire2Service.php


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getItineraire2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.WIErbLc.App\Entity\Itineraire' shared service.
     *
     * @return \App\Entity\Itineraire
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.WIErbLc": it references class "App\\Entity\\Itineraire" but no such service exists.');
    }
}
