<?php

<<<<<<<< Updated upstream:var/cache/dev/Container32wZr7w/getReclamation2Service.php
namespace Container32wZr7w;
========
namespace ContainerXmUnInr;
>>>>>>>> Stashed changes:var/cache/dev/ContainerXmUnInr/getReclamation2Service.php


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getReclamation2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.Ky9OCSE.App\Entity\Reclamation' shared service.
     *
     * @return \App\Entity\Reclamation
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.Ky9OCSE": it references class "App\\Entity\\Reclamation" but no such service exists.');
    }
}
