<?php

<<<<<<<< Updated upstream:var/cache/dev/ContainerS5qyPfw/getReservationService.php
namespace ContainerS5qyPfw;
========
namespace ContainerXmUnInr;
>>>>>>>> Stashed changes:var/cache/dev/ContainerXmUnInr/getReservationService.php


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getReservationService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.jtI7Unb.App\Entity\Reservation' shared service.
     *
     * @return \App\Entity\Reservation
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.jtI7Unb": it references class "App\\Entity\\Reservation" but no such service exists.');
    }
}
