<?php

<<<<<<<< Updated upstream:var/cache/dev/Container32wZr7w/getUtilisateur2Service.php
namespace Container32wZr7w;
========
namespace ContainerXmUnInr;
>>>>>>>> Stashed changes:var/cache/dev/ContainerXmUnInr/getUtilisateur2Service.php


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUtilisateur2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.wxsJsLA.App\Entity\Utilisateur' shared service.
     *
     * @return \App\Entity\Utilisateur
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.wxsJsLA": it references class "App\\Entity\\Utilisateur" but no such service exists.');
    }
}
