<?php

namespace ContainerWobdjq2;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMaintenance2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.onwFewe.App\Entity\Maintenance' shared service.
     *
     * @return \App\Entity\Maintenance
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.onwFewe": it references class "App\\Entity\\Maintenance" but no such service exists.');
    }
}
